# Generated by Django 6.0.3 on 2026-03-24 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('title_am', models.CharField(blank=True, max_length=200, verbose_name='Title (Amharic)')),
                ('description', models.TextField()),
                ('description_am', models.TextField(blank=True, verbose_name='Description (Amharic)')),
                ('listing_type', models.CharField(choices=[('house', 'House'), ('car', 'Car')], max_length=10)),
                ('purpose', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_period', models.CharField(blank=True, default='month', max_length=20)),
                ('area', models.CharField(choices=[('bole', 'Bole / ቦሌ'), ('kirkos', 'Kirkos / ቂርቆስ'), ('kolfe', 'Kolfe Keranio / ቆልፌ ቀራኒዮ'), ('gulele', 'Gulele / ጉለሌ'), ('lideta', 'Lideta / ልደታ'), ('nifas_silk', 'Nifas Silk-Lafto / ንፋስ ስልክ-ላፍቶ'), ('akaky', 'Akaky Kaliti / አቃቂ ቃሊቲ'), ('yeka', 'Yeka / የካ'), ('addis_ketema', 'Addis Ketema / አዲስ ከተማ'), ('arada', 'Arada / አራዳ'), ('lemlem', 'Lemi-Kura / ለሚ-ኩራ'), ('cherkos', 'Cherkos / ጨርቆስ')], max_length=50)),
                ('city', models.CharField(default='Addis Ababa', editable=False, max_length=50)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('floor_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floor_number', models.PositiveIntegerField(blank=True, null=True)),
                ('furnished', models.BooleanField(blank=True, null=True)),
                ('car_make', models.CharField(blank=True, max_length=50)),
                ('car_model', models.CharField(blank=True, max_length=50)),
                ('car_year', models.PositiveIntegerField(blank=True, null=True)),
                ('car_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('car_color', models.CharField(blank=True, max_length=30)),
                ('car_transmission', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('car_fuel', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='listings/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='listings.listing')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
